/* create DATABASE*/
CREATE DATABASE IF NOT EXISTS TEST;

USE TEST;

CREATE TABLE IF NOT EXISTS ADMINISTRATION ( user_id INT AUTO_INCREMENT PRIMARY KEY, login_label VARCHAR(20) UNIQUE NOT NULL, password_label VARCHAR(20) NOT NULL);

INSERT INTO ADMINISTRATION(login_label, password_label) VALUES ('login', 'encryptedpassword');


